hazelcast:

  group:
    name: dev1
    password: dev-pass

  management-center:
    enabled: true
    scripting-enabled: false
    update-interval: 0
    url: http://localhost:8080/hazelcast-mancenter

  map:
    mmap:
      backup-count: 0

  queue:
    bounded:
      max-size: 10

  cp-subsystem:
      cp-member-count: 3