hazelcast:

  group:
    name: dev1
    password: dev-pass

  management-center:
    enabled: true
    scripting-enabled: false
    update-interval: 2
    url: http://localhost:8080/hazelcast-mancenter

  map:
    default:
      backup-count: 2

  queue:
    bounded:
      max-size: 10

  cp-subsystem:
      cp-member-count: 3